export const CATEGORIES = {
    language: [
        'javascript',
        'typescript',
        'python',
        'ruby',
        'php',
        'html',
        'css',
        'sass',
        'solidity',
    ],
    framework: [
        'vue',
        'react',
        'angular',
        'svelte',
        'nuxt',
        'next',
        'express',
        'laravel',
    ],
    database: [
        'mysql',
        'mongodb',
        'postgresql',
        'redis',
        'sqlite',
        'firestore',
        'nosql',
    ],
    design: [
        'bootstrap',
        'tailwindcss',
        'material-ui',
        'chakra-ui',
        'radix-ui',
        'daisyui',
        'fontawesome',
        'bootstrap-icons',
        'chartjs',
    ],
    deployment: [
        'aws',
        'digitalocean',
        'vercel',
        'netlify',
        'heroku',
        'firebase',
        'github-pages',
        'github-actions',
        'kubernetes',
    ],
    tooling: [
        'nodejs',
        'vite',
        'inertiajs',
        'docker',
        'vagrant',
        'webpack',
        'eslint',
        'jest',
        'vuex',
        'rxjs',
    ],
    technology: [
        'rest',
        'graphql',
        'websockets',
        'webassembly',
        'p2p',
        'redux',
        'web3',
        'cryptography',
        'blockchain',
        'proof-of-work',
        'long-polling',
        'sse',
        'ssr',
    ],
};
