name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1        

      - name: Install and Build
        env:
          # NUXT_APP_BASE_URL: '/webceyhan.github.io/'
          GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}
          GITHUB_API_USERNAME: ${{ secrets.API_USERNAME }}
          # social link handles
          USER_GITHUB: ${{ vars.USER_GITHUB }}
          USER_REDDIT: ${{ vars.USER_REDDIT }}
          USER_LINKEDIN: ${{ vars.USER_LINKEDIN }}
          USER_TWITTER: ${{ vars.USER_TWITTER }}
          USER_INSTAGRAM: ${{ vars.USER_INSTAGRAM }}
        run: |
          bun install
          bun run generate
          rm -f .output/public/200.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .output/public # The folder the action should deploy.
